export const SET_POKEMONS = 'SET_POKEMONS';
export const SET_LOADING = 'SET_LOADING';
export const SET_READYCOMBAT = 'SET_READYCOMBAT';
export const SET_VALUESEARCH = 'SET_VALUESEARCH';
export const SET_SEARCH = 'SET_SEARCH';